### ISSUE TITLE
Trying to create a Fork of docker-openluup

### ISSUE THREAD

**Issue by nodecentral** [vwout/docker-openluup#13]
Hi @vwout 

Sorry if you see some strange updates come through from me - as I noticed something to update in your repo, it gave me the option to create a fork, so I did, and I’m now trying to learn what that means and how I create my own flavour , but can also contribute to yours if needed 

I hope that is OK, never done this before, so if you have any advice, it would be appreciated :-)

**Comment by vwout** [comment]
Hi @nodecentral, no problem at all. Your PR looks good, I merged it.
I'm not actively working on or maintaining the image. I took my Vera offline, deactivated all luup code and only use the radio's and ser2net to forward it to Zwave JS and Home Assistant. So feel free to fork and extend.

**Comment by vwout** [comment]
I noticed your comment in https://github.com/akbooer/MetOffice_DataHub/issues/1#issuecomment-2448602837. After merging your fix for dkjson-lua, I updated all repo links and bumped the image base version tot the latest stable. The latest images on Docker Hub are up to date now.

**Comment by nodecentral** [comment]
> I took my Vera offline, deactivated all luup code and only use the radio's and ser2net to forward it to Zwave JS and Home Assistant. So feel free to fork and extend.

Hi vwout, I’d love to learn more about this, is there a particular guide you followed ?

**Comment by vwout** [comment]
I followed these instruction: https://github.com/toggledbits/Vera-Decouple
The Vera (MiCasaVerde/Ezlo) forums contain several discussions on this procedure.

To setup ser2net:

I inserted the following lines to `vi /usr/bin/Start_LuaUPnP.sh` at line 29:
```
log "===BEGIN==="
log "Start ser2net instead of LuaUPnP"
ser2net
exit 0
```

And I added the following 2 lines to `/etc/ser2net.conf`:
```
3333:raw:0:/dev/ttyS0:115200 8DATABITS NONE 1STOPBIT
3300:raw:0:/dev/ttyS2:57600 8DATABITS NONE 1STOPBIT
```

You can setup ZWave-JS by connecting it to tcp://your-vera-ip:3333
