### ISSUE TITLE
Bridged mode

### ISSUE THREAD

**Issue by RHCPNG** [vwout/docker-openluup#2]
Hi vwout,

Another issue/question. I'm trying to create the docker in bridged mode, but that doesn't seem to work. 

Does it only work in host mode? For what I've read about it, bridged mode is preferred above host mode for security reasons and when you have multiple containers on the same host.

**Comment by vwout** [comment]
No it does not only work in host mode, there is no dependency on the networking mode.
What does not work in bridge mode? In the screenshots you added to issue #1, I do not see any port mapping. OpenLuup runs on port 3480, you probably want to map that exposed port.

**Comment by RHCPNG** [comment]
I have mapped the port. It says it is running, but I can't reach openluup via 192.168.1.100:3480.

When I run it in host mode, it does work.

BTW. I don't get any logging. Both the working host mode does not give me logging and the bridged mode also doesn't. With the previous issue with the volumes however I did get some logging.

![image](https://user-images.githubusercontent.com/22906448/50523753-20ba4900-0ad2-11e9-965a-a1fbf448364a.png)

**Comment by vwout** [comment]
My containers run in bridge mode, but I (typically) never specify the host address. Does it work without the host IP?

**Comment by RHCPNG** [comment]
I got it to work, I think I made a mistake when creating the container. I should specify the ip address though. Thanks for your help!

**Comment by vwout** [comment]
Anything worth sharing to help other openmediavault users?

**Comment by RHCPNG** [comment]
Not really, although it's specific to OMV. You have to create a new line after every entry, even though you're not going to use it. That's probably what I forgot.
