### ISSUE TITLE
backup script openluup not working

### ISSUE THREAD

**Issue by RHCPNG** [vwout/docker-openluup#3]
Hi vwout,

Thanks for the great docker! I've been running it for a few months and it runs great. However, I have a scene running in AltUI which triggers the following script in openluup:

/cmh-ludl/cgi-bin/cmh/backup.sh

And I found out that it doesn't work anymore since I migrated to your docker. The script isn't working anymore. 

Can you help me find out what the cause is? Some backups of the user_data.json can be very useful.

Thanks in advance!

**Comment by vwout** [comment]
Hi RHCPNG,

thanks for the heads up.

I had a look and the script `/cmh-ludl/cgi-bin/cmh/backup.sh` does not exist on openLuup. 
On openLuup there is the script `backup.lua` that can be called from AltUI and that performs a similar action (see https://community.getvera.com/t/openluup-tips-tricks/189397/12).

This script can be automatically called as described by akbooer in https://community.getvera.com/t/openluup-tips-tricks/189397/13:
> To run a backup, you just need to issue the HTTP request:
> `http://openLuupIP:3480/cgi-bin/cmh/backup.sh`
> So if you schedule a daily scene with the following Luup code:
> `luup.inet.wget "http://127.0.0.1:3480/cgi-bin/cmh/backup.sh"`

**Comment by RHCPNG** [comment]
That's exactly what I'm doing, but since going to your docker it doesn't work anymore. Does it work for you?

*EDIT*
I see now that calling the URL in my browser DOES work. Apparently from a scene doesn't anymore.

**Comment by RHCPNG** [comment]
Ok, I solved it already. I used my own local URL instead of 127.0.0.1. I changed it to this ip address and now it works fine. 

Thanks for you help!
