### ISSUE TITLE
Feature request: Ping

### ISSUE THREAD

**Issue by RHCPNG** [vwout/docker-openluup#5]
Hi vwout,

Could you please add the iputils-ping package to the docker? Reactor uses it to check internet health.

Thanks!

**Comment by vwout** [comment]
Sure, it was added in commit 91ef69dcadcf207c2780cda07797a68ea59ab7ff in my working version. A new image on [vwout/openluup](https://hub.docker.com/r/vwout/openluup) is on its way.

**Comment by RHCPNG** [comment]
Thanks very much!
