### ISSUE TITLE
Timezone sync?

### ISSUE THREAD

**Issue by perhusaas** [vwout/docker-openluup#8]
How do i get timezone sync with this container? (alpine)
I tried to bind /etc/localtime with no luck.. 

I see that people install tzdata in the dockerfile, I could do that, but i'd prefer using this image if possible..

**Comment by vwout** [comment]
The package `tzdata` is already available in the [alpine[(https://github.com/vwout/docker-openluup/blob/master/openluup-alpine/Dockerfile) image.

To set your timezone, configure `TZ`, one of the [supported environment variables](https://github.com/vwout/docker-openluup#environment). You can e.g. add this to your docker-compose file:
```
    environment:
      - TZ=Europe/Amsterdam
```
Alternatively, you can set it as docker command line argument and you can also use UTC offsets.

**Comment by perhusaas** [comment]
Perfect. thanks!
